on:
  push:
    branches:
      - dev
      - test-new-cd
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: "18.x"
  AZURE_WEBAPP_NAME: ghost-azure-test

jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install --production

      # - name: Create a zip
      #   run: zip -r ghost-azure.zip .
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ github.workspace }}

